package com.enigwed.constant;

public enum ENotificationType {
    ACCOUNT_REGISTRATION,
    ORDER_RECEIVED,
    ORDER_ACCEPTED,
    ORDER_REJECTED,
    ORDER_CANCELLED,
    CONFIRM_PAYMENT,
    ORDER_PAID,
    ORDER_FINISHED,
    ORDER_REVIEWED,
    SUBSCRIPTION_RECEIVED,
    SUBSCRIPTION_CONFIRMED,
}
