version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres-enigwed
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: enigwed_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"  # Local port 5434 to container port 5432
    networks:
      - enigwed_network

  # Spring Boot Application (enigwed)
  enigwed:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SKIP_TESTS: "true"  # Pass an argument to skip tests
    container_name: enigwed
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-enigwed:5432/enigwed_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      IMAGE_PATH: /app/images
    ports:
      - "8082:8080"
    volumes:
      - /home/enigma/asset/images:/app/images  # Mount directory from host to container
    networks:
      - enigwed_network

volumes:
  postgres-data:

networks:
  enigwed_network:
    driver: bridge
